# -*- coding: utf-8 -*-
"""LINEAR REGRESSION USING PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvvb0g_s4nvv4VOad1qFZTYglSWSV7aN
"""

#Implement linear regression using Python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

np.random.seed(0)
x=np.random.rand(100,1) #Generate Random Dataset
y=-2+3*x+np.random.rand(100,1)
regression_model=LinearRegression()
regression_model.fit(x,y)
y_predicted=regression_model.predict(x)
rmse=mean_squared_error(y,y_predicted)
r2=r2_score(y,y_predicted)
print('Slope: ',regression_model.coef_)
print('Intercept: ',regression_model.intercept_)
print('Root Mean Squared: ',rmse)
print('R2 score: ',r2)
plt.scatter(x,y,s=10)
plt.xlabel('x-values from 0-1 ')
plt.ylabel('y-values from 2-5 ')
plt.plot(x,y_predicted,color='g')
plt.show()